### ISSUE TITLE
Change drive input system to be based on joystick twist.

### ISSUE THREAD

**Issue by nandantumu** [team178/2016RobotCode#1]
It's currently based on x-axis movement, and it's odd to use.

**Comment by TheKrunch** [comment]
I agree, as a driver it makes more sense, and it will make the robot easier to control.

**Comment by fivea** [comment]
^ I concur, as a human player.

**Comment by TheKrunch** [comment]
I have added some comments asking questions/posing solutions to this issue. If we look back at TheClaaw code we can see how it was implemented there. `joystick.getTwist()` This is what we are looking for I believe.

**Comment by TheKrunch** [comment]
I have added into the code`zVal = -1*joystick.getTwist();` under where xVal and yVal are declared. (By the way xVal uses joystick.get**y**() and yVal uses joystick.get**x**(), meaning the are pulling the opposite value, not sure if intentional.) I also added:
`//This is the code for twist turning.`

`else if(Math.abs(zVal)>0.1){`
   `left1.set(-zVal);`
   `left2.set(-zVal);`
   `right1.set(-zVal);`
   `right2.set(-zVal);`

As of right now we can now turn by twisting the joystick! I am closing this issue.

**Comment by TheKrunch** [comment]
On further testing it seems that you can not twist while doing other operations. This is because it is a different else if statement. If we combine it with the rest of it it should fix this problem. We also need to remove the left right turning.

**Comment by TheKrunch** [comment]
So, xVal has been removed and has been replaced with twistVal. You should now be able to twist while doing other operations because it is now in the same if statement.
